[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DMQTT_MAX_PACKET_SIZE=512
lib_deps =
  bblanchon/ArduinoJson @ ^7.1.0
  knolleary/PubSubClient @ ^2.8
